name: BUILD

on: [push, pull_request, workflow_dispatch]

jobs:

  job-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            - name: Cache local Maven repository

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - name: Build with Maven
        env:
          TRAVIS_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          TRAVIS_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          TRAVIS_BUILD_NUMBER: ${{ github.run_id }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: mvn install

#  job-notify:
#    if: always()
#    name: Post Workflow Status To Slack
#    needs:
#      - job-build
#    runs-on: ubuntu-latest
#    steps:
#      - uses: Gamesight/slack-workflow-status@master
#        with:
#          repo_token: ${{secrets.GITHUB_TOKEN}}
#          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
